Repository Zulko/moviepy, pull requests merged in 2018-02, with the labels that each got.

#711 More PEP8 compliance
  moviepy/video/VideoClip.py
Labels: refactor

#664 Update Dockerfile to add requests module
  Dockerfile
Labels: tests

#603 Exceptions do not have a .message attribute.
  moviepy/config.py
Labels: bug-fix

#686 Added missing '%' operator for string formatting.
  moviepy/video/io/ffmpeg_tools.py
Labels: bug-fix

#710 res —> size to align with line 62
  moviepy/video/io/ffmpeg_tools.py
Labels: bug-fix

#708 import numpy as np for lines 151 and 178
  moviepy/video/tools/tracking.py
Labels: bug-fix

#709 Add gap=0 to align with lines 40, 97, and 98
  moviepy/video/tools/credits.py
Labels: bug-fix

#717 Resolve undefined name unicode in Python 3
  moviepy/compat.py
  moviepy/video/VideoClip.py
Labels: tests

#718 Resolve undefined name execfile in Python 3
  moviepy/config.py
Labels: bug-fix

#705 flake8 test to find syntax errors, undefined names
  .travis.yml
Labels: tests

#716 Fix credits, added tests
  moviepy/video/tools/credits.py
  tests/test_videotools.py
Labels: bug-fix, tests

#713 Remove testing support for Python 3.3, closes #688
  .travis.yml
  appveyor.yml
  setup.py
Labels: tests

#724 Added tests, new duration arg in to_ImageClip()
  moviepy/video/VideoClip.py
  moviepy/video/io/gif_writers.py
  tests/test_VideoClip.py
Labels: tests
