Repository Zulko/moviepy, pull requests merged in 2020-03, with the labels that each got.

#1018 Add Travis support for Python 3.7 and 3.8
  .travis.yml
  README.rst
  setup.py
  tests/README.rst
  tests/test_TextClip.py
  tests/test_videotools.py
Labels: mergable, tests, travis

#958 Test that the temporary audio file exists
  moviepy/video/VideoClip.py
Labels: LGTM, bug-fix

#968 Reorder FFMPEG_VideoWriter command arguments
  moviepy/video/io/ffmpeg_writer.py
Labels: bug-fix, ffmpeg

#1077 refactor Pythonic sake
  CHANGELOG.md
  moviepy/Clip.py
  moviepy/audio/AudioClip.py
  moviepy/decorators.py
  moviepy/tools.py
  moviepy/utils.py
  moviepy/video/VideoClip.py
  moviepy/video/compositing/CompositeVideoClip.py
  moviepy/video/compositing/concatenate.py
  moviepy/video/fx/crop.py
  moviepy/video/fx/even_size.py
  moviepy/video/fx/freeze.py
  moviepy/video/fx/mask_color.py
  moviepy/video/io/bindings.py
  moviepy/video/io/ffmpeg_reader.py
  moviepy/video/tools/credits.py
  moviepy/video/tools/cuts.py
  moviepy/video/tools/drawing.py
  moviepy/video/tools/segmenting.py
  moviepy/video/tools/subtitles.py
  moviepy/video/tools/tracking.py
  tests/test_AudioClips.py
  tests/test_examples.py
  tests/test_tools.py
Labels: refactor

#1046 Improve afx.audio_normalize documentation
  moviepy/audio/fx/audio_normalize.py
Labels: documentation

#1008 Get ffmpeg to use all audio streams
  moviepy/video/io/ffmpeg_tools.py
Labels: bug-fix, ffmpeg

#795 Fix slide out
  moviepy/video/compositing/transitions.py
Labels: bug-fix

#1090 Remove tqdm as a dependency
  Dockerfile
  README.rst
  docs/install.rst
  moviepy/Clip.py
  moviepy/audio/AudioClip.py
  setup.py
Labels: feature-change

#890 FFmpeg Writer: handle redirected logs when checking for errors
  moviepy/video/io/ffmpeg_writer.py
  tests/test_VideoClip.py
Labels: new-behaviour
