Repository Zulko/moviepy, pull requests merged in 2020-06, with the labels that each got.

#1211 Fix Clip.fx docstring
  moviepy/Clip.py
Labels: documentation

#1212 Fix color_gradient crash
  CHANGELOG.md
  moviepy/video/tools/drawing.py
Labels: bug-fix

#684 Use popen.communicate() to prevent subprocess hang
  moviepy/video/io/ffmpeg_reader.py
Labels: bug-fix

#939 [ffmpeg_tools] removed period from ffmpeg_extract_subclip
  CHANGELOG.md
  moviepy/video/io/ffmpeg_tools.py
Labels: bug-fix

#1063 Video duration fix
  CHANGELOG.md
  moviepy/video/io/ffmpeg_reader.py
Labels: bug-fix

#1220 Rework usage of FFMPEG_VideoReader's `pos` and `lastread`; FFMPEG_AudioReader.close_proc() -> close()
  CHANGELOG.md
  media/test_video.mp4
  moviepy/audio/io/AudioFileClip.py
  moviepy/audio/io/readers.py
  moviepy/video/io/ffmpeg_reader.py
  tests/test_ffmpeg_reader.py
Labels: bug-fix, enhancement

#1237 Ability to set pixel format for video or image files
  CHANGELOG.md
  moviepy/video/VideoClip.py
  moviepy/video/io/VideoFileClip.py
  moviepy/video/io/ffmpeg_reader.py
  moviepy/video/io/ffmpeg_writer.py
  moviepy/video/io/gif_writers.py
  tests/test_VideoClip.py
Labels: new-feature

#1241 Change file extension for audio file and resizing parameters during…
  examples/dancing_knights.py
Labels: examples
