Repository Zulko/moviepy, pull requests merged in 2020-08, with the labels that each got.

#1287 Add Linux test to GitHub actions
  .github/workflows/ci.yml
  .github/workflows/format_check.yml
  .github/workflows/pythonpackage.yml
  .github/workflows/test_suite.yml
  tests/test_examples.py
Labels: tests

#1281 Correct CompositeVideoClip docstring (swap width, height ordering)
  moviepy/video/compositing/CompositeVideoClip.py
Labels: documentation

#959 Add ‘ignore’ for UTF8 decoding to avoid error on non-UTF8 characters
  CHANGELOG.md
  moviepy/video/io/ffmpeg_reader.py
Labels: bug-fix

#1288 Remove BitmapClip.set_fps and .set_duration
  moviepy/video/VideoClip.py
  tests/test_BitmapClip.py
  tests/test_Clip.py
  tests/test_VideoClip.py
  tests/test_compositing.py
  tests/test_fx.py
Labels: feature-change
