Repository Zulko/moviepy, pull requests merged in 2020-04, with the labels that each got.

#1121 Add new 'Unreleased' section to CHANGELOG.md.
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  setup.py
Labels: project structure / organisation

#1119 Fix TextClip.list("color") returning an incorrect list of byte objects, not strings
  CHANGELOG.md
  moviepy/video/VideoClip.py
  tests/test_TextClip.py
Labels: bug-fix

#1120 Fixed errors in docs
  docs/examples/quick_recipes.rst
  docs/gallery.rst
Labels: documentation

#1115 Remove deprecated functions and parameters
  CHANGELOG.md
  moviepy/audio/AudioClip.py
  moviepy/audio/io/ffmpeg_audiowriter.py
  moviepy/editor.py
  moviepy/tools.py
  moviepy/video/VideoClip.py
  moviepy/video/compositing/concatenate.py
  moviepy/video/compositing/transitions.py
  moviepy/video/io/VideoFileClip.py
  moviepy/video/io/ffmpeg_writer.py
  moviepy/video/io/gif_writers.py
  moviepy/video/io/html_tools.py
  moviepy/video/tools/cuts.py
  tests/test_PR.py
Labels: breaking

#1043 Added encoding optional parameter to subtitle file loading feature
  CHANGELOG.md
  moviepy/video/tools/subtitles.py
Labels: new-feature

#1132 Followup to TextClip.list() fix (#1119)
  moviepy/video/VideoClip.py
Labels: refactor

#1139 Fix for `ColorClip.rotate()`
  CHANGELOG.md
  moviepy/video/fx/rotate.py
  tests/test_fx.py
Labels: bug-fix

#589 Add test for detect_scenes
  tests/test_videotools.py
Labels: tests

#1148 deleted outdate opencv install instructions and fixed english syntax
  README.rst
  docs/FAQ.rst
  docs/examples/compo_from_image.rst
  docs/gallery.rst
  docs/getting_started/compositing.rst
  docs/getting_started/effects.rst
  docs/getting_started/efficient_moviepy.rst
  docs/getting_started/quick_presentation.rst
  docs/getting_started/videoclips.rst
  docs/index.rst
  docs/install.rst
  docs/opencv_instructions.rst
  examples/headblur.py
  examples/star_worms.py
  moviepy/audio/fx/all/__init__.py
Labels: documentation

#1137 Add support for path-like objects with a decorator
  CHANGELOG.md
  moviepy/audio/AudioClip.py
  moviepy/audio/io/AudioFileClip.py
  moviepy/decorators.py
  moviepy/video/VideoClip.py
  moviepy/video/io/VideoFileClip.py
  moviepy/video/io/ffmpeg_tools.py
  moviepy/video/tools/credits.py
  moviepy/video/tools/subtitles.py
  tests/test_PR.py
Labels: new-feature

#1153 Fixed a typo
  docs/getting_started/effects.rst
Labels: documentation

#1154 Fixing a few typos
  docs/getting_started/efficient_moviepy.rst
Labels: documentation

#1151 Flake8 formatting cleanup
  .travis.yml
  docs/conf.py
  ez_setup.py
  find_latest_imagemagick_version.py
  moviepy/Clip.py
  moviepy/audio/AudioClip.py
  moviepy/audio/fx/audio_loop.py
  moviepy/audio/io/preview.py
  moviepy/audio/io/readers.py
  moviepy/config.py
  moviepy/config_defaults.py
  moviepy/utils.py
  moviepy/video/VideoClip.py
  moviepy/video/compositing/concatenate.py
  moviepy/video/fx/accel_decel.py
  moviepy/video/fx/even_size.py
  moviepy/video/fx/headblur.py
  moviepy/video/fx/painting.py
  moviepy/video/fx/resize.py
  moviepy/video/fx/rotate.py
  moviepy/video/io/VideoFileClip.py
  moviepy/video/io/ffmpeg_reader.py
  moviepy/video/io/ffmpeg_tools.py
  moviepy/video/io/ffmpeg_writer.py
  moviepy/video/io/html_tools.py
  moviepy/video/io/preview.py
  moviepy/video/io/sliders.py
  moviepy/video/tools/cuts.py
  moviepy/video/tools/segmenting.py
  moviepy/video/tools/subtitles.py
  moviepy/video/tools/tracking.py
  tests/test_AudioClips.py
  tests/test_ImageSequenceClip.py
  tests/test_PR.py
  tests/test_TextClip.py
  tests/test_VideoClip.py
  tests/test_VideoFileClip.py
  tests/test_Videos.py
  tests/test_compositing.py
  tests/test_examples.py
  tests/test_ffmpeg_reader.py
  tests/test_fx.py
  tests/test_issues.py
  tests/test_misc.py
  tests/test_resourcerelease.py
  tests/test_resourcereleasedemo.py
  tests/test_videotools.py
Labels: refactor

#1109 Simpler custom configuration and better related docs
  CHANGELOG.md
  README.rst
  docs/install.rst
  moviepy/audio/io/ffmpeg_audiowriter.py
  moviepy/audio/io/readers.py
  moviepy/config.py
  moviepy/config_defaults.py
  moviepy/video/VideoClip.py
  moviepy/video/io/ffmpeg_reader.py
  moviepy/video/io/ffmpeg_tools.py
  moviepy/video/io/ffmpeg_writer.py
  moviepy/video/io/gif_writers.py
  setup.py
Labels: 3rd-party, breaking, new-feature

#1144 Allow setting tempfile path
  CHANGELOG.md
  moviepy/video/VideoClip.py
  tests/test_VideoClip.py
Labels: new-feature
