Repository Zulko/moviepy, pull requests merged in 2020-10, with the labels that each got.

#1222 Corrections to video duration detection
  CHANGELOG.md
  media/bitmap.mp4
  moviepy/audio/io/AudioFileClip.py
  moviepy/audio/io/readers.py
  moviepy/video/io/VideoFileClip.py
  moviepy/video/io/ffmpeg_reader.py
  moviepy/video/io/html_tools.py
  tests/test_ffmpeg_reader.py
Labels: bug-fix

#1327 Change docs and comments to reflect default fps_source changing from 'tbr' to 'fps'
  moviepy/video/io/VideoFileClip.py
  moviepy/video/io/ffmpeg_reader.py
Labels: documentation

#1328 Add support for ReadTheDocs
  .readthedocs.yml
  setup.py
Labels: documentation

#1331 Add .readthedocs.yml to v1.0.x branch
  .readthedocs.yml
Labels: documentation

#1333 Fix incorrect behaviour from BitmapClip when fps != 1
  CHANGELOG.md
  moviepy/video/VideoClip.py
  tests/test_BitmapClip.py
Labels: bug-fix

#1337 Switch Black GitHub action to the official working version
  .github/workflows/format_check.yml
Labels: tooling

#1105 Fluent API for effects (monkeypatch as methods)
  CHANGELOG.md
  moviepy/audio/AudioClip.py
  moviepy/audio/fx/__init__.py
  moviepy/audio/fx/all/__init__.py
  moviepy/audio/fx/audio_loop.py
  moviepy/editor.py
  moviepy/video/VideoClip.py
  moviepy/video/compositing/transitions.py
  moviepy/video/fx/__init__.py
  moviepy/video/fx/all/__init__.py
  moviepy/video/fx/time_mirror.py
  tests/test_issues.py
Labels: feature

#1335 Fix 90 degrees rotation
  CHANGELOG.md
  moviepy/video/fx/rotate.py
Labels: bug-fix, hacktoberfest-accepted

#1352 update, improve Contributing guidelines
  CONTRIBUTING.md
Labels: documentation, project-admin

#1363 Fix typo in docs
  docs/getting_started/quick_presentation.rst
Labels: documentation
