Repository Zulko/moviepy, pull requests merged in 2020-05, with the labels that each got.

#1173 Use integer division for the resolution of the star worms example video
  examples/star_worms.py
Labels: examples

#1124 Improve VideoClip testing by inspecting numpy frame arrays
  CHANGELOG.md
  moviepy/Clip.py
  moviepy/editor.py
  moviepy/video/VideoClip.py
  moviepy/video/fx/colorx.py
  moviepy/video/fx/even_size.py
  moviepy/video/fx/freeze.py
  moviepy/video/fx/loop.py
  moviepy/video/fx/margin.py
  moviepy/video/fx/rotate.py
  moviepy/video/fx/scroll.py
  moviepy/video/fx/time_mirror.py
  tests/test_BitmapClip.py
  tests/test_Clip.py
  tests/test_VideoClip.py
  tests/test_fx.py
Labels: new-feature, tests

#1172 MacOS CI test
  .github/workflows/pythonpackage.yml
Labels: tests

#1181 Fixed small spelling mistake
  moviepy/audio/AudioClip.py
Labels: documentation

#1108 Fix AudioClip I/O
  CHANGELOG.md
  moviepy/audio/AudioClip.py
  moviepy/audio/io/readers.py
  tests/test_AudioClips.py
Labels: bug-fix

#1165 updated dockerfile dependencies to come from setup.py
  Dockerfile
Labels: bug-fix, docker

#614 Docs fixes: added code back into logo example and fixed a couple of typos
  docs/examples/logo.rst
  docs/getting_started/videoclips.rst
Labels: documentation

#580 Stabilize Video - New functionality
  CHANGELOG.md
  moviepy/video/io/ffmpeg_tools.py
  tests/test_ffmpeg_tools.py
Labels: new-feature

#1147 fixed default value bug on ColorClip
  moviepy/video/VideoClip.py
  moviepy/video/compositing/CompositeVideoClip.py
  tests/test_VideoClip.py
Labels: bug-fix

#1164 Fix write_videofile error handling and update write_audiofile to be comparable
  moviepy/audio/io/ffmpeg_audiowriter.py
  moviepy/video/io/ffmpeg_writer.py
  tests/test_VideoClip.py
Labels: bug-fix

#930 added video and audio bit rate
  CHANGELOG.md
  moviepy/audio/io/readers.py
  moviepy/video/io/ffmpeg_reader.py
  tests/test_AudioClips.py
  tests/test_VideoFileClip.py
  tests/test_ffmpeg_reader.py
Labels: new-feature

#1176 Add VideoClip.set_layer()
  CHANGELOG.md
  moviepy/video/VideoClip.py
  moviepy/video/compositing/CompositeVideoClip.py
  tests/test_VideoClip.py
Labels: new-feature

#1190 Update deprecated function in documentation
  docs/getting_started/quick_presentation.rst
Labels: documentation

#1041 autodetect ImageMagick on windows
  moviepy/config.py
Labels: imagemagick, new-feature

#796 FIX: concatenate - duration of the result
  moviepy/video/compositing/concatenate.py
Labels: bug-fix

#1200 Call resize on mask when newsize is a function of time
  CHANGELOG.md
  moviepy/video/fx/resize.py
Labels: bug-fix

#1207 Fix appveyor build: remove pipenv
  appveyor.yml
Labels: tests

#1201 Prevent exception when filename is given.
  CHANGELOG.md
  moviepy/video/VideoClip.py
Labels: bug-fix
