Repository Zulko/moviepy, pull requests merged in 2022-10, with the labels that each got.

#1836 change 'set_pos' to 'with_position'
  examples/moving_letters.py
Labels: refactor

#1841 Fix Windows CI
  scripts/get-latest-imagemagick-win.py
Labels: tooling

#1788 Fix textclip filename parameter in wrong format
  moviepy/video/VideoClip.py
  tests/test_TextClip.py
Labels: bug-fix, lib-ImageMagick

#1842 Raise `ValueError` if invalid arguments passed to `TextClip`
  CHANGELOG.md
  moviepy/video/VideoClip.py
  tests/test_TextClip.py
Labels: enhancement
